-- 1. Crear y seleccionar la base de datos
CREATE DATABASE IF NOT EXISTS tienda_peliculas CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE tienda_peliculas;

-- 2. Tablas Independientes (Maestras)
CREATE TABLE USUARIO (
    ID_USUARIO INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR(200) NOT NULL,
    FECHA_REGISTRO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ROL VARCHAR(20) NOT NULL DEFAULT 'CLIENTE'
);

CREATE TABLE GENERO (
    ID_GENERO INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(40) NOT NULL UNIQUE
);

CREATE TABLE ACTOR (
    ID_ACTOR INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(150) NOT NULL
);

CREATE TABLE DIRECTOR (
    ID_DIRECTOR INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(150) NOT NULL
);

-- 3. Tabla Central (Película)
CREATE TABLE PELICULA (
    ID_PELICULA INTEGER PRIMARY KEY AUTO_INCREMENT,
    TITULO VARCHAR(100) NOT NULL,
    DESCRIPCION TEXT,
    AÑO INTEGER NOT NULL,
    PRECIO_COMPRA DECIMAL(5,2) NOT NULL,
    PRECIO_RENTA DECIMAL(5,2) NOT NULL,
    COPIAS_RENTA_DISPONIBLES INTEGER NOT NULL DEFAULT 0,
    COPIAS_VENTA_DISPONIBLES INTEGER NOT NULL DEFAULT 0,
    IMAGEN VARCHAR(300)
);

-- 4. Tablas de Unión (Con CASCADE)
CREATE TABLE PELICULA_GENERO (
    ID_PELICULA INTEGER NOT NULL,
    ID_GENERO INTEGER NOT NULL,
    PRIMARY KEY (ID_PELICULA, ID_GENERO),
    FOREIGN KEY (ID_PELICULA) REFERENCES PELICULA(ID_PELICULA) ON DELETE CASCADE,
    FOREIGN KEY (ID_GENERO) REFERENCES GENERO(ID_GENERO) ON DELETE CASCADE
);

CREATE TABLE PELICULA_ACTOR (
    ID_PELICULA INTEGER NOT NULL,
    ID_ACTOR INTEGER NOT NULL,
    PRIMARY KEY (ID_PELICULA, ID_ACTOR),
    FOREIGN KEY (ID_PELICULA) REFERENCES PELICULA(ID_PELICULA) ON DELETE CASCADE,
    FOREIGN KEY (ID_ACTOR) REFERENCES ACTOR(ID_ACTOR) ON DELETE CASCADE
);

CREATE TABLE PELICULA_DIRECTOR (
    ID_PELICULA INTEGER NOT NULL,
    ID_DIRECTOR INTEGER NOT NULL,
    PRIMARY KEY (ID_PELICULA, ID_DIRECTOR),
    FOREIGN KEY (ID_PELICULA) REFERENCES PELICULA(ID_PELICULA) ON DELETE CASCADE,
    FOREIGN KEY (ID_DIRECTOR) REFERENCES DIRECTOR(ID_DIRECTOR) ON DELETE CASCADE
);

-- 5. Tablas Transaccionales (Con reglas mixtas)

-- Sistema de Reseñas
CREATE TABLE RESEÑA (
    ID_RESEÑA INTEGER PRIMARY KEY AUTO_INCREMENT,
    COMENTARIO TEXT,
    CALIFICACION INTEGER NOT NULL CHECK (CALIFICACION >= 1 AND CALIFICACION <= 5),
    FECHA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ID_PELICULA INTEGER NOT NULL,
    ID_USUARIO INTEGER NULL, -- Cambiado a NULLABLE
    
    FOREIGN KEY (ID_PELICULA) REFERENCES PELICULA(ID_PELICULA) ON DELETE CASCADE,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO) ON DELETE SET NULL,
    UNIQUE (ID_PELICULA, ID_USUARIO)
);

-- Carrito de Compras (Temporal)
CREATE TABLE CARRITO (
    ID_CARRITO INTEGER PRIMARY KEY AUTO_INCREMENT,
    CANTIDAD INTEGER NOT NULL DEFAULT 1,
    TIPO_DE_TRANSACCION VARCHAR(10) NOT NULL,
    ID_USUARIO INTEGER NOT NULL,
    ID_PELICULA INTEGER NOT NULL,
    
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE,
    FOREIGN KEY (ID_PELICULA) REFERENCES PELICULA(ID_PELICULA) ON DELETE CASCADE,
    UNIQUE (ID_USUARIO, ID_PELICULA, TIPO_DE_TRANSACCION)
);

-- Pedidos (Registro histórico)
CREATE TABLE PEDIDO (
    PEDIDO_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    FECHA_PEDIDO DATE NOT NULL,
    MONTO_TOTAL DECIMAL(10,2) NOT NULL,
    ESTADO VARCHAR(40) NOT NULL DEFAULT 'Completado',
    ID_USUARIO INTEGER NULL, -- Cambiado a NULLABLE
    
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO) ON DELETE SET NULL
);

-- Detalle de cada pedido (Registro histórico)
CREATE TABLE DETALLE_PEDIDO (
    DETALLE_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    PRECIO DECIMAL(10,2) NOT NULL,
    TIPO_DE_TRANSACCION VARCHAR(10) NOT NULL,
    CANTIDAD INTEGER NOT NULL,
    PEDIDO_ID INTEGER NOT NULL,
    ID_PELICULA INTEGER NOT NULL,
    
    FOREIGN KEY (PEDIDO_ID) REFERENCES PEDIDO(PEDIDO_ID) ON DELETE CASCADE,
    -- NO hay 'ON DELETE' aquí a propósito. Protege tu historial de ventas
    -- si una película es borrada del catálogo.
    FOREIGN KEY (ID_PELICULA) REFERENCES PELICULA(ID_PELICULA)
);