apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-peliculas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: monsoropeza/backend-peliculas:prod-final 
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
        env:
        - name: DB_HOST
          value: "mysql-service"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "monseSQL"
        - name: DB_NAME
          value: "tienda_peliculas"
        - name: DB_PORT
          value: "3306"

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
      nodePort: 30001