apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-scripts
data:
  init.sql: |
    -- 1. Crear base de datos
    CREATE DATABASE IF NOT EXISTS tienda_peliculas CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
    USE tienda_peliculas;

    -- 2. Tablas Independientes (Maestras) - EN MAYUSCULAS
    CREATE TABLE IF NOT EXISTS USUARIO (
        ID_USUARIO INTEGER PRIMARY KEY AUTO_INCREMENT,
        NOMBRE VARCHAR(100) NOT NULL,
        EMAIL VARCHAR(100) NOT NULL UNIQUE,
        PASSWORD VARCHAR(200) NOT NULL,
        FECHA_REGISTRO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        ROL VARCHAR(20) NOT NULL DEFAULT 'CLIENTE'
    );

    CREATE TABLE IF NOT EXISTS GENERO (
        ID_GENERO INTEGER PRIMARY KEY AUTO_INCREMENT,
        NOMBRE VARCHAR(40) NOT NULL UNIQUE
    );

    CREATE TABLE IF NOT EXISTS ACTOR (
        ID_ACTOR INTEGER PRIMARY KEY AUTO_INCREMENT,
        NOMBRE VARCHAR(150) NOT NULL
    );

    CREATE TABLE IF NOT EXISTS DIRECTOR (
        ID_DIRECTOR INTEGER PRIMARY KEY AUTO_INCREMENT,
        NOMBRE VARCHAR(150) NOT NULL
    );

    -- 3. Tabla Central (Película) - CAMBIADO AÑO POR ANIO
    CREATE TABLE IF NOT EXISTS PELICULA (
        ID_PELICULA INTEGER PRIMARY KEY AUTO_INCREMENT,
        TITULO VARCHAR(100) NOT NULL,
        DESCRIPCION TEXT,
        ANIO INTEGER NOT NULL, 
        PRECIO_COMPRA DECIMAL(5,2) NOT NULL,
        PRECIO_RENTA DECIMAL(5,2) NOT NULL,
        COPIAS_RENTA_DISPONIBLES INTEGER NOT NULL DEFAULT 0,
        COPIAS_VENTA_DISPONIBLES INTEGER NOT NULL DEFAULT 0,
        IMAGEN VARCHAR(300)
    );

    -- 4. Tablas de Unión
    CREATE TABLE IF NOT EXISTS PELICULA_GENERO (
        ID_PELICULA INTEGER NOT NULL,
        ID_GENERO INTEGER NOT NULL,
        PRIMARY KEY (ID_PELICULA, ID_GENERO),
        FOREIGN KEY (ID_PELICULA) REFERENCES PELICULA(ID_PELICULA) ON DELETE CASCADE,
        FOREIGN KEY (ID_GENERO) REFERENCES GENERO(ID_GENERO) ON DELETE CASCADE
    );

    CREATE TABLE IF NOT EXISTS PELICULA_ACTOR (
        ID_PELICULA INTEGER NOT NULL,
        ID_ACTOR INTEGER NOT NULL,
        PRIMARY KEY (ID_PELICULA, ID_ACTOR),
        FOREIGN KEY (ID_PELICULA) REFERENCES PELICULA(ID_PELICULA) ON DELETE CASCADE,
        FOREIGN KEY (ID_ACTOR) REFERENCES ACTOR(ID_ACTOR) ON DELETE CASCADE
    );

    CREATE TABLE IF NOT EXISTS PELICULA_DIRECTOR (
        ID_PELICULA INTEGER NOT NULL,
        ID_DIRECTOR INTEGER NOT NULL,
        PRIMARY KEY (ID_PELICULA, ID_DIRECTOR),
        FOREIGN KEY (ID_PELICULA) REFERENCES PELICULA(ID_PELICULA) ON DELETE CASCADE,
        FOREIGN KEY (ID_DIRECTOR) REFERENCES DIRECTOR(ID_DIRECTOR) ON DELETE CASCADE
    );

    -- 5. Tablas Transaccionales - CAMBIADO RESEÑA POR RESENIA
    CREATE TABLE IF NOT EXISTS RESENIA (
        ID_RESENIA INTEGER PRIMARY KEY AUTO_INCREMENT,
        COMENTARIO TEXT,
        CALIFICACION INTEGER NOT NULL CHECK (CALIFICACION >= 1 AND CALIFICACION <= 5),
        FECHA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        ID_PELICULA INTEGER NOT NULL,
        ID_USUARIO INTEGER NULL,
        FOREIGN KEY (ID_PELICULA) REFERENCES PELICULA(ID_PELICULA) ON DELETE CASCADE,
        FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO) ON DELETE SET NULL,
        UNIQUE (ID_PELICULA, ID_USUARIO)
    );

    CREATE TABLE IF NOT EXISTS CARRITO (
        ID_CARRITO INTEGER PRIMARY KEY AUTO_INCREMENT,
        CANTIDAD INTEGER NOT NULL DEFAULT 1,
        TIPO_DE_TRANSACCION VARCHAR(10) NOT NULL,
        ID_USUARIO INTEGER NOT NULL,
        ID_PELICULA INTEGER NOT NULL,
        FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE,
        FOREIGN KEY (ID_PELICULA) REFERENCES PELICULA(ID_PELICULA) ON DELETE CASCADE,
        UNIQUE (ID_USUARIO, ID_PELICULA, TIPO_DE_TRANSACCION)
    );

    CREATE TABLE IF NOT EXISTS PEDIDO (
        PEDIDO_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
        FECHA_PEDIDO DATE NOT NULL,
        MONTO_TOTAL DECIMAL(10,2) NOT NULL,
        ESTADO VARCHAR(40) NOT NULL DEFAULT 'Completado',
        ID_USUARIO INTEGER NULL,
        FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO) ON DELETE SET NULL
    );

    CREATE TABLE IF NOT EXISTS DETALLE_PEDIDO (
        DETALLE_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
        PRECIO DECIMAL(10,2) NOT NULL,
        TIPO_DE_TRANSACCION VARCHAR(10) NOT NULL,
        CANTIDAD INTEGER NOT NULL,
        PEDIDO_ID INTEGER NOT NULL,
        ID_PELICULA INTEGER NOT NULL,
        FOREIGN KEY (PEDIDO_ID) REFERENCES PEDIDO(PEDIDO_ID) ON DELETE CASCADE,
        FOREIGN KEY (ID_PELICULA) REFERENCES PELICULA(ID_PELICULA)
    );

    CREATE TABLE IF NOT EXISTS sessions (
        session_id varchar(128) COLLATE utf8mb4_bin NOT NULL,
        expires int(11) unsigned NOT NULL,
        data mediumtext COLLATE utf8mb4_bin,
        PRIMARY KEY (session_id)
    );

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  ports:
  - port: 3306
  clusterIP: None
  selector:
    app: mysql-db

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-db
spec:
  serviceName: "mysql-service"
  replicas: 1
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "monseSQL"
        - name: MYSQL_DATABASE
          value: "tienda_peliculas"
        volumeMounts:
        - name: init-scripts
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: init-scripts
        configMap:
          name: mysql-init-scripts